### ISSUE TITLE
Walk.py is broken

### ISSUE THREAD

**Issue by BelloqZafarian** [nickdogedeveloper/ToontownOffline#2]
For some reason my Walk.py keeps crashing my client. Help!

**Comment by MrCheeze446** [comment]
Have you tried deleting Walk.py?

**Comment by dubitosmom** [comment]
[walk.zip](https://github.com/nickdogedeveloper/ToontownOffline/files/2891092/walk.zip)
my son dubito hasn't provided the correct walk.py! here you go
